title = "jutty.dev"
description = "Computer nerd memory leaks"
author = "Juno Takano"
base_url = "https://blog.jutty.dev"
default_language = "en"

generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [
  { name = "tags", feed = true },
]

[translations]
[languages]

[languages.pt]
generate_feeds = true
feed_filenames = ["atom.xml"]
title = "jutty.dev"
description = "Vazamentos de uma memória nerd-computante"

[markdown]
smart_punctuation = true
bottom_footnotes = true

[markdown.highlighting]
theme = "night-owl"
style = "class"

[extra]
title_separator = "-"
